### PR TITLE
[COMP] feature: allow small ("sm") breakpoint support for `buildBreakpointClassnames`

### LINKED ISSUE #100: buildBreakpointClassNames: remove grid opinions
The `buildBreakpointClassnames` helper is AWESOME, but it needs to be less opinionated. Currently it only generates classes for medium-up, but there's not a great reason to do that — as "medium-up" is a grid-specific convention that we use.

## Goal
I would like to be able to add classes for `small-only` as an example. `<ChildSpacing>`, for example (still to-do), will often need spacing for the small breakpoint only (when columns stack vertically).

## Suggestion:
- add more breakpoint options to this helper — `sm`, `sm-only `, etc.

### Caveat
This will break the grid layout classname generation, so we'll need to update that a bit

### PR DESCRIPTION
**Pull request by andrewrubin**
## Description

This builds out the `buildBreakpointClassnames` helper a little bit, allowing for an optional `sm` property on the optional `prop` object. The motivation for this fix was to — by default — have the generated classnames encompass _all_ breakpoints, rather than starting a medium (which was a bit too opinionated to the grid-layout system).

## Solution

You can now do something like
```jsx
<YourComponent propName={{ sm: "yes", md: "no", lg: "maybe" }}>
```
which will generate the following classnames: `.propName-yes`, `.propName-md-no`, and `propName-lg-maybe`.

## Notes
- Tested the Grid Layout system for regressions, and it still works perfectly 🎉 
- The solution I added _only_ accounts for the addition of the `sm` property, and adds or removed the `md-` classname prefix based on the availability of said property. There is definitely a more robust solution floating out there in space — something that does a fancy loop and creates prefixes based on the availability of _all_ breakpoint properties — but as I got into it, I decided it's smarter to just solve for our needs now and in the foreseeable future; rather than over-engineer things.
- This is a branch of the already-merged feature in #181 — thus the redundant changes to the `Flex` stylesheet.

## Does this close any existing issues?
Closes #100 
Referenced in #181 and #172 as well

## Screenshots

Here's an example using the `<Flex>` component, and the newly available `sm` property. The difference between this and our current implementation is that there's now a difference between the small and medium breakpoints:

https://github.com/wethegit/component-library/assets/30575213/741c0a42-f983-401f-b1a0-b81373f695a3

### CODE REVIEW

**Comment by marlonmarcello** [comment]
@andrewrubin thanks for the changes, this is looking great. I think that we should just always require the `-` prefix. This way there is no ambiguity for contributors or confusion for component users.

**Comment by marlonmarcello** [comment]
These classes are generated with functions anyways, it's not like we are having to painstakingly update each one, so might as well make it a standard.

**Comment by andrewrubin** [comment]
Good plan. So, to retrofit our grid-layout per your suggestion, we'll simply add the `md-` prefix to the stylesheet? I'll do that now if so.

**Comment by andrewrubin** [comment]
@marlonmarcello that's added — so we're now always adding the prefix (except on small, since, mobile-first 😉 ), and I've updated the `<Column>` classnames to reflect that.

**Comment by marlonmarcello** [comment]
@andrewrubin I think we should add to small too mate. That way there is absolutely no questioning IF/WHEN/WHERE, they are always there, on all classes with breakpoints.

**Comment by andrewrubin** [comment]
For sure, added the `sm` prefix as well!

**Review by marlonmarcello — APPROVED** [review]

**Pull request merged**
